### ISSUE TITLE
Creating new circles 

### ISSUE THREAD

**Issue by nkzarrabi** [kerkeslager/friendzone#68]
IntegrityError at /circles/new
NOT NULL constraint failed: core_circle.color

**Comment by kerkeslager** [comment]
@nkzarrabi I built a fix for a different error on creating Circles, but the error I was getting was different. I suspect you were seeing that error because your db schema was wrong. Before submitting bugs from database errors, try blowing away your database and re-migrating it--we're changing the database too rapidly right now to keep a big backlog of migrations.
